@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.nihilhalla.drinkbeer.utilsborrowedfromMdiyo.fluid.transfer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
