modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/Nihilhalla/DrinkBeer-ByTheBuckets/issues"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="drinkbeer"
    version="${version}"
    displayName="Drink Beer by the Buckets"
    authors="Nihilhalla"
    description='''
A mod about drinking beer, what more do you need?
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/drink-beer-by-the-buckets"
    
[[dependencies.drinkbeer]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.drinkbeer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.drinkbeer]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.drinkbeer]]
    modId="jei"
    mandatory=false
    versionRange="${jei_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.drinkbeer]]
    modId="jsonthings"
    mandatory=false
    versionRange="${json_things_range}"
    ordering="NONE"
    side="BOTH"