@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.nihilhalla.drinkbeer.utilsborrowedfromMdiyo.client.render;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
