@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.nihilhalla.drinkbeer.utilsborrowedfromMdiyo.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
