@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.nihilhalla.drinkbeer.utilsborrowedfromMdiyo.client.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
