@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.nihilhalla.drinkbeer.utilsborrowedfromMdiyo.fluid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
